---

- name: Run PowerShell
  hosts: "{{ _hosts | default('os_windows') }}"
  gather_facts: false
  vars:
    ps_script: undef

  tasks:
    - name: Run PowerShell
      register: ps_output
      ansible.windows.win_powershell:
        script: |
          {{ ps_script | regex_replace('^"|"$', '') }}

    - name: Print output
      ansible.builtin.debug:
        msg: "{{ ps_output.output }}"
